#!/usr/bin/env node
//
// Emit mainnet-ready sources for the STX-rewards suite, plus a Clarinet
// deployment plan that publishes them.
//
//   node scripts/build-mainnet.mjs                       # -> build/mainnet/*.clar + deployments/stx-rewards.mainnet-plan.yaml
//   DEPLOYER=SP... node scripts/build-mainnet.mjs
//   clarinet deployments apply -p deployments/stx-rewards.mainnet-plan.yaml
//
// WHY THIS EXISTS
//
// The contracts in contracts/ are written against the TESTNET pox-5 principal,
// `ST000000000000000000002AMW42H.pox-5`, because that is the address the
// vendored boot copy and the simnet tests use. On mainnet the very same boot
// contract lives at `SP000000000000000000002Q6VF78.pox-5`. Publishing the
// testnet-addressed source to mainnet fails analysis: the trait it implements
// would not resolve.
//
// The sBTC and DEX principals need no rewriting -- they are already the mainnet
// ones, which is exactly why `clarinet check` can type-check the adapters
// against the real routers.
//
// This script does that one substitution and nothing else, so a reviewer can
// diff build/mainnet against contracts/ and see a single changed principal per
// file.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';

const TESTNET_POX5 = 'ST000000000000000000002AMW42H';
const MAINNET_POX5 = 'SP000000000000000000002Q6VF78';

// Publish order matters: `dex-traits` defines the traits the others use, and
// the signer manager must exist before an adapter is allowlisted against it.
// `mock-dex-adapter` is absent on purpose -- it is a test fixture.
const SUITE = [
  ['dex-traits', 'contracts/dex-traits.clar'],
  ['fastpool-stx-rewards', 'contracts/stx-rewards.clar'],
  ['price-oracle-jing', 'contracts/price-oracle-jing.clar'],
  ['dex-adapter-bitflow-dlmm', 'contracts/dex-adapter-bitflow-dlmm.clar'],
  ['dex-adapter-bitflow-xyk', 'contracts/dex-adapter-bitflow-xyk.clar'],
];

const deployer = process.env.DEPLOYER ?? 'SPMPMA1V6P430M8C91QS1G9XJ95S59JS1TZFZ4Q4';
const outDir = 'build/mainnet';
mkdirSync(outDir, { recursive: true });

const rewritten = [];
for (const [name, path] of SUITE) {
  const src = readFileSync(path, 'utf8');
  const out = src.split(TESTNET_POX5).join(MAINNET_POX5);
  const hits = src.split(TESTNET_POX5).length - 1;
  writeFileSync(`${outDir}/${name}.clar`, out);
  rewritten.push({ name, path, out: `${outDir}/${name}.clar`, hits });
  console.log(`${name.padEnd(26)} ${String(hits).padStart(3)} pox-5 principal(s) rewritten  -> ${outDir}/${name}.clar`);
}

// Sanity: nothing may still point at the testnet boot address.
for (const r of rewritten) {
  if (readFileSync(r.out, 'utf8').includes(TESTNET_POX5)) {
    console.error(`FATAL: ${r.out} still references ${TESTNET_POX5}`);
    process.exit(1);
  }
}

const plan = `id: 0
name: fastpool-stx-rewards mainnet deployment
network: mainnet
stacks-node: https://api.hiro.so
bitcoin-node: http://blockstack:blockstacksystem@bitcoin.blockstack.com:8332
# GENERATED by scripts/build-mainnet.mjs -- do not hand-edit; regenerate instead.
#
# Sources come from build/mainnet/, which is contracts/ with the pox-5 principal
# rewritten from the testnet boot address to the mainnet one. Diff the two trees
# before applying; the only difference should be that principal.
#
# After applying, the suite still needs its admin wiring before it can run a
# cycle -- see docs/deploy-stx-rewards.md:
#   set-price-oracle, set-max-slippage-bips, set-dex-adapter (x2),
#   set-operator, update-fees, register-self
plan:
  batches:
${SUITE.map(([name], i) => `  - id: ${i}
    transactions:
    - transaction-type: contract-publish
      contract-name: ${name}
      expected-sender: ${deployer}
      cost: 500000
      path: ${outDir}/${name}.clar
      anchor-block-only: true
      clarity-version: 6
    epoch: '4.0'`).join('\n')}
`;
writeFileSync('deployments/stx-rewards.mainnet-plan.yaml', plan);
console.log('\nwrote deployments/stx-rewards.mainnet-plan.yaml');
console.log(`deployer: ${deployer}  (override with DEPLOYER=SP...)`);
